# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# UnCSS will use these settings (Uncss can damage animations effects!)
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"

  # clear dist folder not touching heroku files
  delete_dist_options:
    - "dist/**/*"
    - "!dist/composer.json"
    - "!dist/index.php"
    - "!dist/.git"
    - "!dist/.git/**/*"

  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}"
    - "!src/assets/{img,js,scss}/**/*"

  # Content here will be copied to the root
  to_root:
    - "src/to-root/**/*"

  # Images 
  images:
    - "src/assets/img/**/*"
    - "!src/assets/img/sprites/**/*"
    - "!src/assets/img/sprites"

  # Paths to use in gulp.watch due to probable performance issue 
  watch_styles:
    - "src/assets/scss/**/*.scss"

  #Sprites
  sprites:
  - "src/assets/img/sprites/"

  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # jquery 3
    - "src/assets/js/vendor/jquery/jquery-3.3.1.js"
    # Bootstrap 4 js
    - "src/assets/js/vendor/bootstrap4/bootstrap.bundle.js"
    # Slick 1.8.0
    - "src/assets/js/vendor/slick/slick.js"

    # Paths to your own project code are here
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"

    # if not need js to be processed, comment paths above and uncomment below
    #- "src/assets/js/**/*"
