# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
#  # Foundation
#   - "last 2 versions"
#   - "ie >= 9"
#   - "ios >= 7"
#  # Boostrap 3
#   - "Android 2.3"
#   - "Android >= 4"
#   - "Chrome >= 20"
#   - "Firefox >= 24"
#   - "Explorer >= 8"
#   - "iOS >= 6"
#   - "Opera >= 12"
#   - "Safari >= 6"
   #Boostrap 4
  - "Android 2.3"
  - "Android >= 4"
  - "Chrome >= 26"
  - "Firefox >= 38"
  - "Edge >= 12"
  - "Explorer >= 10"
  - "iOS >= 8"
  - "Opera >= 12"
  - "Safari >= 8"

# UnCSS will use these settings (Uncss can damage animations effects!)
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    # Foundation
#     - !!js/regexp .foundation-mq
#     - !!js/regexp ^\.is-.*
#    #   motion UI
#     - !!js/regexp ^\.(fade|slide|hinge|scale|spin)
#     - !!js/regexp ^\.mui-.*
    ## Bootstrap3
#    - !!js/regexp \w\.in
#    - '.fade'
#    - '.collapse'
#    - '.collapsing'
#    - !!js/regexp (#|\.)navbar(\-[a-zA-Z]+)?
#    - !!js/regexp (#|\.)dropdown(\-[a-zA-Z]+)?
#    - !!js/regexp (#|\.)(open)
#    - !!js/regexp (#|\.)carousel(\-[a-zA-Z]+)?
#    - '.modal'
#    - '.modal.fade.in'
#    - '.modal-dialog'
#    - '.modal-document'
#    - '.modal-scrollbar-measure'
#    - '.modal-backdrop.fade'
#    - '.modal-backdrop.in'
#    - '.modal.fade.modal-dialog'
#    - '.modal.in.modal-dialog'
#    - '.modal-open'
#    - '.in'
#    - '.modal-backdrop'
#    - !!js/regexp \.affix
#    - !!js/regexp \.alert
#    - !!js/regexp \.close
#    - !!js/regexp \.has
#    - !!js/regexp \.help
#    - !!js/regexp \.popover
#    - !!js/regexp \.tooltip
#    - !!js/regexp \.in
#    - !!js/regexp \.slick
#    #Custom
#    - '.overflow-toggle'
#    - !!js/regexp \.lg
#    #Bootstrap4
#    #todo Google it!

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # clear dist folder not touching heroku files
  delete_dist_options:
    - "dist/**/*"
    - "!dist/composer.json"
    - "!dist/index.php"
    - "!dist/.git"
    - "!dist/.git/**/*"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}"
    - "!src/assets/{img,js,scss}/**/*"
  # Content here will be copied to the root
  to_root:
    - "src/to-root/**/*"
  # Images 
  images:
    - "src/assets/img/**/*"
    - "!src/assets/img/sprites/**/*"
    - "!src/assets/img/sprites"
  # Paths to use in gulp.watch due to probable performance issue 
  watch_styles:
    - "src/assets/scss/*.scss"
    - "src/assets/scss/components/*.scss"
    - "src/assets/scss/pages/*.scss"
    - "src/assets/scss/utils/*.scss"
    - "src/assets/scss/vendor/*.scss"
  #Sprites
  sprites:
  - "src/assets/img/sprites/"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:

   #BOOTSTRAP4 scss
     - "node_modules/bootstrap/scss"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Common libraries
    # jquery 3
    - "node_modules/jquery/dist/jquery.js"

    # Bootstrap 4 js
    - "node_modules/bootstrap/dist/js/bootstrap.bundle.js"

    # Paths to your own project code are here
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"
